version: "3.9"

services:
  auth:
    build:
      context: ./../auth
      dockerfile: Dockerfile
    image: skn1942/eshop-auth
    ports:
      - 9000:9000
    expose:
      - 9000    
    environment:
      - MONGO_URI=mongodb://auth-mongodb:27017/auth
      - MONGO_PORT=27017
      - MONGO_DB_NAME=auth
      - JWT_KEY=ThisIsATestJWTKey
    volumes:
      - ./../auth:/app

  auth-mongodb:
      image: mongo:latest
      ports:
        - 27017:27017
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: root
      #   MONGO_INITDB_ROOT_PASSWORD: testPassword1234
      volumes:
      - auth-data:/data/db/
  prometheus:
    build: 
      dockerfile: prometheus.dockerfile
      context: ./../monitoring/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./../monitoring/prometheus/prometheus-config.yml:/etc/prometheus/prometheus-config.yml
    env_file:
      - ./../monitoring/prometheus/prometheus.env

  grafana:
    build: 
      dockerfile: grafana.dockerfile
      context: ./../monitoring/grafana
    container_name: grafana
    user: "472"
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./../monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./../monitoring/grafana/config.monitoring
      - ./../monitoring/grafana/grafana.env


volumes:
  auth-data:
