export enum Subjects {
  TEST = "TEST",
  UserCheckoutAccepted = 'UserCheckoutAccepted',
  OrderStarted = "OrderStarted",
  ProdcutPriceChanged = "ProductPriceChanged",
  OrderStockRejected = "OrderStockRejected",
  OrderStockConfirmed = "OrderStockConfirmed",
  OrderStatusChangedToAwaitingValidation = "OrderStatusChangedToAwaitingValidation",
  OrderStatusChangedToPaid = "OrderStatusChangedToPaid",
  OrderStatusChangedToStockConfirmed = "OrderStatusChangedToStockConfirmed",
  OrderPaymentFailed = "OrderPaymentFailed",
  OrderPaymentSucceeded = "OrderPaymentSucceeded",
  OrderStatusChangedToShipped = "OrderStatusChangedToShipped",
  OrderStatusChangedToCancelled = "OrderStatusChangedToCancelled",
}
